#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building livescript files ..."
cat src/form.ls src/condctrl.ls src/manager.ls src/op.ls src/widget.ls src/module.ls > dist/form.ls
./node_modules/.bin/lsc -cp dist/form.ls > dist/index.js
echo "minifying form.js ..."
./node_modules/.bin/uglifyjs dist/index.js > dist/index.min.js
rm dist/form.ls

echo "copy dist to web ..."
rm -rf web/static/assets/lib/@plotdb/form/dev/
mkdir -p web/static/assets/lib/@plotdb/form/dev/
cp -R dist/* web/static/assets/lib/@plotdb/form/dev/
ln -s dev web/static/assets/lib/@plotdb/form/main
rm web/static/assets/lib/@plotdb/form/dev/dev
