 (function() { function pug_rethrow(e,n,r,t){if(!(e instanceof Error))throw e;if(!("undefined"==typeof window&&n||t))throw e.message+=" on line "+r,e;var o,a,i,s;try{t=t||require("fs").readFileSync(n,{encoding:"utf8"}),o=3,a=t.split("\n"),i=Math.max(r-o,0),s=Math.min(a.length,r+o)}catch(t){return e.message+=" - could not read from "+n+" ("+t.message+")",void pug_rethrow(e,null,r)}o=a.slice(i,s).map(function(e,n){var t=n+i+1;return(t==r?"  > ":"    ")+t+"| "+e}).join("\n"),e.path=n;try{e.message=(n||"Pug")+":"+r+"\n"+o+"\n\n"+e.message}catch(e){}throw e}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {;pug_debug_line = 1;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fconfig\u002Ftext\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv\u003E";
;pug_debug_line = 2;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fconfig\u002Ftext\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv plug=\"config\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fconfig\u002Ftext\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cinput class=\"form-control\" ld=\"input\"\u002F\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 5;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fconfig\u002Ftext\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cscript type=\"@plotdb\u002Fblock\"\u003E";
;pug_debug_line = 5;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fconfig\u002Ftext\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "(function(it){\n  return it();\n})(function(){\n  var blockFactory;\n  blockFactory = {\n    pkg: {\n      name: 'config\u002Ftext',\n      version: '0.0.1',\n      extend: {\n        name: 'config\u002Fbase',\n        version: '0.0.1'\n      },\n      dependencies: [],\n      i18n: {\n        \"zh-TW\": {\n          \"text for comparison\": \"比較用的文字\"\n        }\n      }\n    },\n    init: function(arg$){\n      var root, context, data, pubsub, t, ldview, view;\n      root = arg$.root, context = arg$.context, data = arg$.data, pubsub = arg$.pubsub, t = arg$.t;\n      ldview = context.ldview;\n      pubsub.fire('init', {\n        get: function(){\n          return view.get('input').value || '';\n        },\n        set: function(it){\n          return view.get('input').value = it || '';\n        }\n      });\n      return view = new ldview({\n        root: root,\n        init: {\n          input: function(arg$){\n            var node;\n            node = arg$.node;\n            node.value = data['default'] || '';\n            return node.setAttribute('placeholder', t(data.hint || 'text for comparison'));\n          }\n        },\n        action: {\n          input: {\n            input: function(arg$){\n              var node;\n              node = arg$.node;\n              return pubsub.fire('event', 'change', node.value);\n            }\n          },\n          change: {\n            input: function(arg$){\n              var node;\n              node = arg$.node;\n              return pubsub.fire('event', 'change', node.value);\n            }\n          }\n        }\n      });\n    }\n  };\n  return blockFactory;\n});\u003C\u002Fscript\u003E\u003C\u002Fdiv\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line);};return pug_html;}; module.exports = template; })() 