 (function() { function pug_attr(t,e,n,r){if(!1===e||null==e||!e&&("class"===t||"style"===t))return"";if(!0===e)return" "+(r?t:t+'="'+t+'"');var f=typeof e;return"object"!==f&&"function"!==f||"function"!=typeof e.toJSON||(e=e.toJSON()),"string"==typeof e||(e=JSON.stringify(e),n||-1===e.indexOf('"'))?(n&&(e=pug_escape(e))," "+t+'="'+e+'"'):" "+t+"='"+e.replace(/'/g,"&#39;")+"'"}
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;
function pug_rethrow(e,n,r,t){if(!(e instanceof Error))throw e;if(!("undefined"==typeof window&&n||t))throw e.message+=" on line "+r,e;var o,a,i,s;try{t=t||require("fs").readFileSync(n,{encoding:"utf8"}),o=3,a=t.split("\n"),i=Math.max(r-o,0),s=Math.min(a.length,r+o)}catch(t){return e.message+=" - could not read from "+n+" ("+t.message+")",void pug_rethrow(e,null,r)}o=a.slice(i,s).map(function(e,n){var t=n+i+1;return(t==r?"  > ":"    ")+t+"| "+e}).join("\n"),e.path=n;try{e.message=(n||"Pug")+":"+r+"\n"+o+"\n\n"+e.message}catch(e){}throw e}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {;pug_debug_line = 1;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"rounded-lg shadow mb-4\"\u003E";
;pug_debug_line = 2;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"p-4\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"d-flex\"\u003E";
;pug_debug_line = 4;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"flex-grow-1\"\u003E";
;pug_debug_line = 5;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"d-flex align-items-end mb-1\"\u003E";
;pug_debug_line = 6;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Ch3 class=\"mb-0\" ld=\"title\" contenteditable=\"true\"\u003E";
;pug_debug_line = 6;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "問題的標題\u003C\u002Fh3\u003E";
;pug_debug_line = 7;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"flex-grow-1 d-flex\"\u003E";
;pug_debug_line = 8;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"text-danger pl-2\" ld=\"required\"\u003E";
;pug_debug_line = 8;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "";
;pug_debug_line = 8;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 8;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "*\u003C\u002Fspan\u003E";
;pug_debug_line = 8;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003C\u002Fdiv\u003E";
;pug_debug_line = 9;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"text-success d-none pl-2\" ld=\"ok-hint\"\u003E";
;pug_debug_line = 9;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Ci class=\"i-check\"\u003E\u003C\u002Fi\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 10;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cp contenteditable=\"true\"\u003E";
;pug_debug_line = 10;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "關於問題的簡單描述 ...\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 11;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv ld=\"edit-only\"\u003E";
;pug_debug_line = 12;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"ml-4\"\u003E";
;pug_debug_line = 12;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown\" ld=\"dropdown\"\u003E";
;pug_debug_line = 13;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"btn btn-light dropdown-toggle\" ld=\"shortname\" data-toggle=\"dropdown\"\u003E";
;pug_debug_line = 13;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "代稱\u003C\u002Fdiv\u003E";
;pug_debug_line = 14;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-menu dropdown-menu-right shadow-sm\"\u003E";
;pug_debug_line = 15;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-header\"\u003E";
;pug_debug_line = 15;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "常用範例\u003C\u002Fdiv\u003E";
;pug_debug_line = 16;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-item\" ld=\"set-shortname\" data-value=\"統一編號\"\u003E";
;pug_debug_line = 16;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "統一編號\u003C\u002Fdiv\u003E";
;pug_debug_line = 17;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-item\" ld=\"set-shortname\" data-value=\"電話\"\u003E";
;pug_debug_line = 17;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "電話\u003C\u002Fdiv\u003E";
;pug_debug_line = 18;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-item\" ld=\"set-shortname\" data-value=\"團隊名稱\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "團隊名稱\u003C\u002Fdiv\u003E";
;pug_debug_line = 19;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-divider\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 20;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-header\"\u003E";
;pug_debug_line = 20;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "自訂名稱\u003C\u002Fdiv\u003E";
;pug_debug_line = 21;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-item px-3\"\u003E";
;pug_debug_line = 21;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cinput class=\"form-control\" ld=\"custom-shortname\" placeholder=\"自訂 ...\"\u002F\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 22;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cplug name=\"view\"\u003E\u003C\u002Fplug\u003E";
;pug_debug_line = 23;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"text-danger py-2 d-none\" ld=\"error-hint\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 24;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"border-top border-bottom\" ld=\"edit-only\"\u003E";
;pug_debug_line = 25;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"m-4\"\u003E";
;pug_debug_line = 26;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"d-flex mb-1 align-items-center justify-content-between\" ld-each=\"term\"\u003E";
;pug_debug_line = 27;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"mr-2\"\u003E";
;pug_debug_line = 27;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"switch switch-lg\" ld=\"enabled\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 28;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"mr-2\"\u003E";
;pug_debug_line = 29;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown\" ld=\"dropdown\"\u003E";
;pug_debug_line = 30;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"btn btn-light dropdown-toggle\" ld=\"opset\" data-toggle=\"dropdown\"\u003E";
;pug_debug_line = 30;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "...\u003C\u002Fdiv\u003E";
;pug_debug_line = 31;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-menu\"\u003E";
;pug_debug_line = 32;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-item\" ld-each=\"set-opset\"\u003E";
;pug_debug_line = 32;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "...\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 33;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"mr-2\"\u003E";
;pug_debug_line = 33;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown\" ld=\"dropdown\"\u003E";
;pug_debug_line = 34;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"btn btn-light dropdown-toggle\" ld=\"op\" data-toggle=\"dropdown\"\u003E";
;pug_debug_line = 34;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "...\u003C\u002Fdiv\u003E";
;pug_debug_line = 35;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-menu\"\u003E";
;pug_debug_line = 36;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"dropdown-item\" ld-each=\"set-op\"\u003E";
;pug_debug_line = 36;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "...\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 37;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv" + (" class=\"d-flex flex-grow-1\""+pug_attr("ld-scope", true, true, false)+" ld=\"config-root\"") + "\u003E";
;pug_debug_line = 38;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"mr-2 flex-grow-1\" ld-each=\"config\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 39;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"mr-2 flex-grow-1\"\u003E";
;pug_debug_line = 40;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cinput class=\"form-control simple\" ld=\"errmsg\" t=\"error message\" t-attr=\"placeholder\"\u002F\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 41;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Ci class=\"i-close text-danger clickable\" ld=\"delete\"\u003E\u003C\u002Fi\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 42;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"mt-4\"\u003E";
;pug_debug_line = 42;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"btn btn-link p-0\" ld=\"add-term\"\u003E";
;pug_debug_line = 42;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "";
;pug_debug_line = 42;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cspan t=\"add criteria\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 42;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + " ...\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 43;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"px-4 pb-4 mt-4\" ld=\"edit-only\"\u003E";
;pug_debug_line = 44;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cplug name=\"config\"\u003E\u003C\u002Fplug\u003E";
;pug_debug_line = 45;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"d-flex align-items-center mt-4\"\u003E";
;pug_debug_line = 46;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"mr-2\"\u003E";
;pug_debug_line = 46;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"btn btn-sm btn-outline-danger\" ld=\"delete\"\u003E";
;pug_debug_line = 46;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "";
;pug_debug_line = 46;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Ci class=\"i-close\"\u003E\u003C\u002Fi\u003E";
;pug_debug_line = 46;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + " ";
;pug_debug_line = 46;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cspan t=\"delete\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 46;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 47;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"mr-2\"\u003E";
;pug_debug_line = 47;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"btn btn-sm btn-outline-secondary\" ld=\"clone\"\u003E";
;pug_debug_line = 47;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "";
;pug_debug_line = 47;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Ci class=\"i-clone\"\u003E\u003C\u002Fi\u003E";
;pug_debug_line = 47;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + " ";
;pug_debug_line = 47;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cspan t=\"copy\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 47;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 48;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"flex-grow-1 justify-content-end d-flex\"\u003E";
;pug_debug_line = 49;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"ml-4 d-flex align-items-center line-height-1em\"\u003E";
;pug_debug_line = 50;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cspan t=\"public\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 51;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"switch ml-2\" ld=\"switch\" data-name=\"isPublic\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 52;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"ml-4 d-flex align-items-center line-height-1em\"\u003E";
;pug_debug_line = 53;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cspan t=\"required\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 54;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"switch ml-2 on\" ld=\"switch\" data-name=\"isRequired\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 56;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cscript type=\"@plotdb\u002Fblock\"\u003E";
;pug_debug_line = 56;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Fbase\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "(function(it){\n  return it();\n})(function(){\n  var blockFactory, mod;\n  blockFactory = {\n    pkg: {\n      name: \"base\",\n      version: \"0.0.1\",\n      dependencies: [\n        {\n          url: \"\u002Fassets\u002Flib\u002Fbootstrap.native\u002Fmain\u002Fbootstrap-native-v4.min.js\"\n        }, {\n          url: \"\u002Fassets\u002Flib\u002F@plotdb\u002Fsuuid\u002Fmain\u002Fsuuid.bundle.min.js\"\n        }, {\n          url: \"\u002Fassets\u002Flib\u002F@plotdb\u002Fkonfig\u002Fmain\u002Fkonfig.min.js\"\n        }, {\n          url: \"\u002Fassets\u002Flib\u002F@Plotdb\u002Fform\u002Fdev\u002Fform.js\"\n        }, {\n          url: \"\u002Fassets\u002Flib\u002Fldview\u002Fmain\u002Findex.min.js\"\n        }\n      ],\n      i18n: {\n        \"zh-TW\": {\n          required: \"必填\",\n          copy: \"複製\",\n          'delete': \"刪除\",\n          'public': \"公開\",\n          \"show description\": \"顯示描述\",\n          \"number for comparison\": \"比較用的數字\",\n          \"add criteria\": \"增加條件\",\n          \"error message\": \"錯誤訊息\",\n          \"invalid input\": \"輸入不符合要求\"\n        }\n      }\n    },\n    'interface': function(){\n      return this.widget;\n    },\n    init: function(opt){\n      var root, pubsub, i18n, form, this$ = this;\n      opt == null && (opt = {});\n      root = opt.root, pubsub = opt.pubsub, i18n = opt.i18n;\n      form = opt.context.form;\n      return pubsub.on('init', function(initOpt){\n        var widget, node;\n        initOpt == null && (initOpt = {});\n        this$.widget = widget = new form.widget({\n          root: root,\n          opsets: initOpt.opsets,\n          mod: mod(opt, initOpt)\n        });\n        i18n.addResourceBundles(this$.widget.i18n);\n        node = {\n          view: root.querySelector('[ld-scope][plug=view]')\n        };\n        return {\n          widget: widget,\n          node: node\n        };\n      });\n    }\n  };\n  mod = function(opt, initOpt){\n    var ref$, BSN, ldview, suuid, form, konfig, pubsub, t, root, mod;\n    opt == null && (opt = {});\n    initOpt == null && (initOpt = {});\n    ref$ = opt.context, BSN = ref$.BSN, ldview = ref$.ldview, suuid = ref$.suuid, form = ref$.form, konfig = ref$.konfig;\n    pubsub = opt.pubsub, t = opt.t, root = opt.root;\n    mod = initOpt.mod;\n    return {\n      render: function(){\n        this._custom.view.render();\n        if (mod && mod.render) {\n          return mod.render.apply(this, args);\n        }\n      },\n      isEmpty: function(){\n        var args, res$, i$, to$;\n        res$ = [];\n        for (i$ = 0, to$ = arguments.length; i$ \u003C to$; ++i$) {\n          res$.push(arguments[i$]);\n        }\n        args = res$;\n        if (mod && mod.isEmpty) {\n          return mod.isEmpty.apply(this, args);\n        }\n      },\n      init: function(){\n        var meta, view, this$ = this;\n        meta = this._meta;\n        this._custom.view = view = new ldview({\n          root: root,\n          action: {\n            input: {\n              title: function(arg$){\n                var node, ctx;\n                node = arg$.node, ctx = arg$.ctx;\n                return meta.title = node.value || '';\n              },\n              desc: function(arg$){\n                var node, ctx;\n                node = arg$.node, ctx = arg$.ctx;\n                return meta.desc = node.value || '';\n              },\n              \"custom-shortname\": function(arg$){\n                var node, views;\n                node = arg$.node, views = arg$.views;\n                meta.alias = node.value || '';\n                return views[0].render();\n              }\n            },\n            click: {\n              \"set-shortname\": function(arg$){\n                var node, views;\n                node = arg$.node, views = arg$.views;\n                meta.alias = node.getAttribute('data-value') || '';\n                return views[0].render();\n              },\n              \"custom-shortname\": function(arg$){\n                var evt;\n                evt = arg$.evt;\n                return evt.stopPropagation();\n              },\n              \"add-term\": function(arg$){\n                var views;\n                views = arg$.views;\n                (meta.term || (meta.term = [])).push(new form.term({\n                  opset: this$._opsets[0]\n                }));\n                this$.validate();\n                return views[0].render('term');\n              },\n              'switch': function(arg$){\n                var node, n;\n                node = arg$.node;\n                n = node.getAttribute('data-name');\n                (meta.config || (meta.config = {}))[n] = !meta.config[n];\n                pubsub.fire('update');\n                return view.render();\n              }\n            }\n          },\n          init: {\n            dropdown: function(arg$){\n              var node;\n              node = arg$.node;\n              return new BSN.Dropdown(node);\n            }\n          },\n          text: {\n            \"shortname\": function(){\n              return meta.alias || '設定代稱..';\n            }\n          },\n          handler: {\n            required: function(arg$){\n              var node;\n              node = arg$.node;\n              return node.classList.toggle('d-none', !meta.config.isRequired);\n            },\n            \"add-term\": function(arg$){\n              var node;\n              node = arg$.node;\n              return node.classList.toggle('d-none', !this$._opsets.length);\n            },\n            \"ok-hint\": function(arg$){\n              var node;\n              node = arg$.node;\n              return node.classList.toggle('d-none', this$._mode === 'edit' || this$._errors.length);\n            },\n            \"error-hint\": function(arg$){\n              var node;\n              node = arg$.node;\n              node.classList.toggle('d-none', this$._mode === 'edit' || !this$._errors.length);\n              return node.textContent = this$._errors.length ? t(this$._errors[0] || \"invalid input\") : '';\n            },\n            \"edit-only\": function(arg$){\n              var node;\n              node = arg$.node;\n              return node.classList.toggle('d-none', this$._mode !== 'edit');\n            },\n            \"set-shortname\": function(arg$){\n              var node;\n              node = arg$.node;\n              return node.classList.toggle('active', node.getAttribute('data-value') === meta.alias);\n            },\n            \"custom-shortname\": function(arg$){\n              var node;\n              node = arg$.node;\n              return node.value = meta.alias || '';\n            },\n            title: function(arg$){\n              var node;\n              node = arg$.node;\n              return node.value = meta.title || '';\n            },\n            desc: function(arg$){\n              var node;\n              node = arg$.node;\n              return node.value = meta.desc || '';\n            },\n            'switch': function(arg$){\n              var node, n;\n              node = arg$.node;\n              n = node.getAttribute('data-name');\n              return node.classList.toggle('on', !!(meta.config || (meta.config = {}))[n]);\n            },\n            term: {\n              list: function(){\n                return meta.term || (meta.term = []);\n              },\n              view: {\n                action: {\n                  input: {\n                    \"errmsg\": function(arg$){\n                      var node, ctx;\n                      node = arg$.node, ctx = arg$.ctx;\n                      return ctx.msg = node.value || '';\n                    }\n                  },\n                  click: {\n                    enabled: function(arg$){\n                      var ctx, views;\n                      ctx = arg$.ctx, views = arg$.views;\n                      ctx.enabled = !ctx.enabled;\n                      return views[0].render();\n                    },\n                    'delete': function(arg$){\n                      var ctx, views;\n                      ctx = arg$.ctx, views = arg$.views;\n                      meta.term.splice(meta.term.indexOf(ctx), 1);\n                      return views[1].render('term');\n                    }\n                  },\n                  change: {\n                    attr: function(arg$){\n                      var node, ctx, views;\n                      node = arg$.node, ctx = arg$.ctx, views = arg$.views;\n                      ctx.opset = meta.attr[node.value].opset;\n                      return views[0].render();\n                    },\n                    op: function(arg$){\n                      var node, views, ctx;\n                      node = arg$.node, views = arg$.views, ctx = arg$.ctx;\n                      ctx.op = form.opset.get(ctx.opset || 'number').getOp(node.value);\n                      return views[0].render();\n                    }\n                  }\n                },\n                init: {\n                  dropdown: function(arg$){\n                    var node;\n                    node = arg$.node;\n                    return new BSN.Dropdown(node);\n                  },\n                  \"config-root\": function(arg$){\n                    var node, ctx, local, cfg;\n                    node = arg$.node, ctx = arg$.ctx, local = arg$.local;\n                    local.cfg = cfg = new konfig({\n                      root: node,\n                      config: ctx.op.config,\n                      name: function(it){\n                        return \"config\u002F\" + it;\n                      }\n                    });\n                    cfg.init();\n                    return cfg.on('change', function(it){\n                      return ctx.config = it;\n                    });\n                  }\n                },\n                text: {\n                  opset: function(arg$){\n                    var ctx;\n                    ctx = arg$.ctx;\n                    return t(!ctx.opset\n                      ? \"\"\n                      : ctx.opset.name || ctx.opset.id);\n                  },\n                  op: function(arg$){\n                    var ctx;\n                    ctx = arg$.ctx;\n                    return t(!ctx.op\n                      ? \"\"\n                      : ctx.op.name || ctx.op.id);\n                  }\n                },\n                handler: {\n                  \"config-root\": function(arg$){\n                    var node, ctx, local, cfg, k, v, show;\n                    node = arg$.node, ctx = arg$.ctx, local = arg$.local;\n                    cfg = ctx.op.config || {};\n                    for (k in cfg) {\n                      v = cfg[k];\n                      if (v.hint) {\n                        v.hint = t(v.hint);\n                      }\n                    }\n                    local.cfg.config(cfg);\n                    if (local.cfg.view) {\n                      local.cfg.view.render();\n                    }\n                    show = !!(function(){\n                      var results$ = [];\n                      for (k in cfg) {\n                        results$.push(k);\n                      }\n                      return results$;\n                    }()).length;\n                    node.classList.toggle('d-none', !show);\n                    return node.classList.toggle('d-flex', show);\n                  },\n                  enabled: function(arg$){\n                    var node, ctx;\n                    node = arg$.node, ctx = arg$.ctx;\n                    return node.classList.toggle('on', !!ctx.enabled);\n                  },\n                  \"set-op\": {\n                    list: function(arg$){\n                      var ctx;\n                      ctx = arg$.ctx;\n                      return ctx.opset.getOps();\n                    },\n                    action: {\n                      click: function(arg$){\n                        var data, ctx, views;\n                        data = arg$.data, ctx = arg$.ctx, views = arg$.views;\n                        ctx.setOp(data.id);\n                        return views[0].render();\n                      }\n                    },\n                    handler: function(arg$){\n                      var node, data;\n                      node = arg$.node, data = arg$.data;\n                      node.textContent = t(data.name || data.id);\n                      return node.setAttribute('data-id', data.id);\n                    }\n                  },\n                  \"set-opset\": {\n                    list: function(){\n                      return this$._opsets;\n                    },\n                    key: function(it){\n                      return it.id;\n                    },\n                    action: {\n                      click: function(arg$){\n                        var data, ctx, views;\n                        data = arg$.data, ctx = arg$.ctx, views = arg$.views;\n                        if (ctx.opset.id === data.id) {\n                          return;\n                        }\n                        ctx.setOpset(data);\n                        return views[0].render();\n                      }\n                    },\n                    handler: function(arg$){\n                      var node, data;\n                      node = arg$.node, data = arg$.data;\n                      node.textContent = t(data.name || data.id);\n                      return node.setAttribute('data-id', data.id);\n                    }\n                  }\n                }\n              }\n            }\n          }\n        });\n        if (mod && mod.init) {\n          return mod.init.apply(this, args);\n        }\n      }\n    };\n  };\n  return blockFactory;\n});\u003C\u002Fscript\u003E\u003C\u002Fdiv\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line);};return pug_html;}; module.exports = template; })() 