 (function() { function pug_attr(t,e,n,r){if(!1===e||null==e||!e&&("class"===t||"style"===t))return"";if(!0===e)return" "+(r?t:t+'="'+t+'"');var f=typeof e;return"object"!==f&&"function"!==f||"function"!=typeof e.toJSON||(e=e.toJSON()),"string"==typeof e||(e=JSON.stringify(e),n||-1===e.indexOf('"'))?(n&&(e=pug_escape(e))," "+t+'="'+e+'"'):" "+t+"='"+e.replace(/'/g,"&#39;")+"'"}
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;
function pug_rethrow(e,n,r,t){if(!(e instanceof Error))throw e;if(!("undefined"==typeof window&&n||t))throw e.message+=" on line "+r,e;var o,a,i,s;try{t=t||require("fs").readFileSync(n,{encoding:"utf8"}),o=3,a=t.split("\n"),i=Math.max(r-o,0),s=Math.min(a.length,r+o)}catch(t){return e.message+=" - could not read from "+n+" ("+t.message+")",void pug_rethrow(e,null,r)}o=a.slice(i,s).map(function(e,n){var t=n+i+1;return(t==r?"  > ":"    ")+t+"| "+e}).join("\n"),e.path=n;try{e.message=(n||"Pug")+":"+r+"\n"+o+"\n\n"+e.message}catch(e){}throw e}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {;pug_debug_line = 1;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv\u003E";
;pug_debug_line = 2;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv" + (" class=\"form-long-answer\""+pug_attr("ld-scope", true, true, false)+" plug=\"view\"") + "\u003E";
;pug_debug_line = 3;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"mb-2\" ld=\"if-markdown-enabled\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"d-flex align-items-center\"\u003E";
;pug_debug_line = 4;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"d-flex align-items-center text-sm text-muted mr-4\" style=\"line-height:1em\"\u003E";
;pug_debug_line = 5;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cinput class=\"mr-1\" type=\"checkbox\" ld=\"use-markdown\"\u002F\u003E";
;pug_debug_line = 6;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv\u003E";
;pug_debug_line = 7;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cspan class=\"mr-2\" t=\"enable markdown\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 8;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 8;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "(\u003C\u002Fspan\u003E";
;pug_debug_line = 9;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Ca class=\"mx-2\" href=\"https:\u002F\u002Fmarkdown.tw\u002F\" target=\"_blank\" rel=\"noopener noreferrer\" t=\"syntax\"\u003E\u003C\u002Fa\u003E";
;pug_debug_line = 10;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cspan\u003E";
;pug_debug_line = 10;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + ")\u003C\u002Fspan\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 11;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"d-none\" ld=\"if-markdown\"\u003E";
;pug_debug_line = 11;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"d-flex align-items-center text-sm text-muted mr-4\" style=\"line-height:1em\"\u003E";
;pug_debug_line = 12;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cinput class=\"mr-1\" type=\"checkbox\" ld=\"toggle-preview\"\u002F\u003E";
;pug_debug_line = 13;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv t=\"preview\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 14;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"position-relative\"\u003E";
;pug_debug_line = 15;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Ctextarea class=\"form-control\" rows=\"5\" ld=\"input-field edit-panel\"\u003E\u003C\u002Ftextarea\u003E";
;pug_debug_line = 16;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"w-100 bg-light rounded p-3 text-break d-none\" ld=\"preview-panel\" style=\"min-height:150px\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 17;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv plug=\"config\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"d-none flex-grow-1\" ld=\"edit-only\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"text-nowrap d-flex align-items-center\"\u003E";
;pug_debug_line = 19;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"mr-2\" t=\"provide markdown option\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 20;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv\u003E";
;pug_debug_line = 20;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cdiv class=\"switch ml-2\" ld=\"switch\" data-name=\"markdownEnabled\"\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 22;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "\u003Cscript type=\"@plotdb\u002Fblock\"\u003E";
;pug_debug_line = 22;pug_debug_filename = "src\u002Fpug\u002Fblock\u002Flong-answer\u002F0.0.1\u002Findex.pug";
pug_html = pug_html + "({\n  pkg: {\n    name: \"long-answer\",\n    version: \"0.0.1\",\n    extend: {\n      name: \"base\",\n      version: \"0.0.1\"\n    },\n    license: \"MIT\",\n    description: \"\",\n    dependencies: [\"https:\u002F\u002Fcdnjs.cloudflare.com\u002Fajax\u002Flibs\u002Fmarked\u002F1.2.7\u002Fmarked.min.js\", \"https:\u002F\u002Fcdnjs.cloudflare.com\u002Fajax\u002Flibs\u002Fdompurify\u002F2.2.6\u002Fpurify.min.js\"],\n    i18n: {\n      \"zh-TW\": {\n        \"input text\": \"輸入文字 ...\",\n        \"provide markdown option\": \"提供 Markdown 選項\",\n        \"preview\": \"預覽\",\n        \"enable markdown\": \"啟用 Markdown 語法\",\n        \"syntax\": \"語法說明\"\n      }\n    }\n  },\n  init: function(arg$){\n    var root, parent, context, pubsub, DOMPurify, marked, ldview, data, value, local, view;\n    root = arg$.root, parent = arg$.parent, context = arg$.context, pubsub = arg$.pubsub;\n    DOMPurify = context.DOMPurify, marked = context.marked, ldview = context.ldview;\n    data = parent.data;\n    data.config || (data.config = {});\n    value = {\n      value: '',\n      useMarkdown: false\n    };\n    local = {};\n    pubsub.on('change', function(it){\n      import$(value, it || {});\n      return view.get('input-field').value = value.value || '';\n    });\n    pubsub.on('update', function(){\n      if (!data.config.markdownEnabled) {\n        value.useMarkdown = false;\n      }\n      return view.render();\n    });\n    return view = new ldview({\n      root: parent.node(),\n      action: {\n        input: {\n          'input-field': function(arg$){\n            var node;\n            node = arg$.node;\n            parent.value(node.value, !node.value, true);\n            return value.value = node.value;\n          }\n        },\n        click: {\n          \"use-markdown\": function(arg$){\n            var node;\n            node = arg$.node;\n            value.useMarkdown = data.config.markdownEnabled && node.checked;\n            return view.render();\n          },\n          \"markdown-enabled\": function(arg$){\n            var node, evt;\n            node = arg$.node, evt = arg$.evt;\n            return data.config.markdownEnabled = !data.config.markdownEnabled;\n          },\n          \"toggle-preview\": function(arg$){\n            var node;\n            node = arg$.node;\n            local.preview = node.checked;\n            return view.render();\n          }\n        }\n      },\n      handler: {\n        \"if-markdown\": function(arg$){\n          var node;\n          node = arg$.node;\n          return node.classList.toggle('d-none', !value.useMarkdown);\n        },\n        \"if-markdown-enabled\": function(arg$){\n          var node;\n          node = arg$.node;\n          return node.classList.toggle('d-none', !data.config.markdownEnabled);\n        },\n        \"use-markdown\": function(arg$){\n          var node;\n          node = arg$.node;\n          return node.checked = value.useMarkdown;\n        },\n        \"preview-panel\": function(arg$){\n          var node;\n          node = arg$.node;\n          node.classList.toggle('d-none', !local.preview);\n          if (local.preview) {\n            return node.innerHTML = DOMPurify.sanitize(marked(value.value || ''));\n          }\n        },\n        \"edit-panel\": function(arg$){\n          var node;\n          node = arg$.node;\n          return node.classList.toggle('d-none', !!local.preview);\n        }\n      }\n    });\n  }\n});\nfunction import$(obj, src){\n  var own = {}.hasOwnProperty;\n  for (var key in src) if (own.call(src, key)) obj[key] = src[key];\n  return obj;\n}\u003C\u002Fscript\u003E\u003C\u002Fdiv\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line);};return pug_html;}; module.exports = template; })() 